### ISSUE TITLE
Deckbuilder

### ISSUE THREAD

**Issue by onecrayon** [onecrayon/ashes.live#6]
## Tasks

* [x] Update deck listings for "my decks" pages
    * [x] Link to private deck details page for Reborn decks
    * [x] Add "Edit" button to select a deck for editing in the builder
    * [x] Add "Delete" button to completely delete the deck (pending support from API!)
    * [x] Link to private deck details page for Legacy decks
* [x] Design the Deck store
    * [x] Should we allow persistent deck building? I think this is a really cool idea that would completely change how people use the site, but it might be a bit too much for the initial release. It would also decouple the deckbuilder from a URL structure. The downside is that the normal card browser isn't actually particularly appropriate for deckbuilding since you don't want things that you cannot add (like PBs, conjurations, and unrelated PB uniques).
* [x] Implement the deckbuilder
    * [x] Build slide-in component on right of page that shows the main deckbuilder interface when it's enabled
        * [x] Animate in and out
        * [x] Toggle visibility and ensure fit on all pages at all screen sizes
        * [x] Ensure it works on mobile (and is anchored at the top of the viewport instead of the page, but still offers scrolling)
        * [x] Edit title
        * [x] Display Phoenixborn
        * [x] Edit and display dice
        * [x] Card listing (with quantity buttons)
        * [x] Edit description
        * [x] Export deck as plain text (port functionality from legacy site; important to have for basic Ashteki integration)
    * [x] Card component
        * [x] Button for adding or swapping a PB
        * [x] Buttons for adjusting quantity for non-PB, PB uniques in deck, non-Conjuration cards
        * [x] Fix shadow on card hovers when quantity buttons are attached (see upper right corner)
    * [x] Card table listing row
        * [x] Button for adding or swapping a PB
        * [x] Buttons for adjusting quantity for non-PB, PB uniques in deck, non-Conjuration cards
    * [x] Card detail page
        * [x] Button for adding or swapping a PB
        * [x] Buttons for adjusting quantity for non-PB, PB uniques in deck, non-Conjuration cards
* [x] Replace deck in the deckbuilder with another deck
* [x] Figure out how to debounce edits to the deck such that we can make a bunch of edits really quickly, but only have a single save request sent

## Follow-up tasks:

* Clone decks
* Generate snapshots (including public snapshots) and snapshot viewing support
* Tools to export to TTS/Ashteki
* First Five and effect cost picker and stats generation; should this be a standalone page? And maybe make this a follow-up task, since it isn't critical to using the deck-builder

## Notes

First Five controls need to be integrated into the standard deck view page. That way we can persist the changes we make to the currently-edited deck, allow people to publish suggestions for their public snapshots, and most importantly allow playing around with alternate First Fives for random public decks (without persistence).

Snapshot history view needs to provide a "diff" between any two consecutive snapshots (so that you can see at a glance what was added or removed). Should it be possible to copy an entire snapshot from the history into the currently edited deck?

**Comment by onecrayon** [comment]
@FabienDeshayes Forgot to mention:

* Please don't bother with any of the TTS logic; I need to come up with something better than what the playtesting build is doing for the actual site. Integrating with Ashteki and TTS is high on my priority list once the basic site functionality is back (maybe even before then; that would be a huge quality-of-life improvement in these COVID times)
* Basic log-in logic is in `features/decks`! You can login with the username/password `hello@ashes.live` / `changeme`
* You're going to need to run the following commands against your local API to reset your database because I screwed up the Streamable table (which means you can't create any new decks/snapshots until you've replaced your local data, and I upped the dependencies; note that `make migrate` and `make example-data` now automatically clean networks before they run):
    ```
    $ make clean
    $ docker volume rm apiasheslive_pgdata
    $ make build
    $ make migrate REV='6b6df338dfc3'
    $ make example-data
    $ make migrate
    ```
